// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq5JGJ_9F90jmqEfZ1ac7JqYyodIA7Om4',
    appId: '1:27116360434:web:926a689f227db09243766b',
    messagingSenderId: '27116360434',
    projectId: 'thix-id',
    authDomain: 'thix-id.firebaseapp.com',
    storageBucket: 'thix-id.firebasestorage.app',
    measurementId: 'G-C0SZGLX5FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpBpwxtZDuRd-Fzp7BcV8HvUWExGZZsA',
    appId: '1:27116360434:android:5e44da9f1323350943766b',
    messagingSenderId: '27116360434',
    projectId: 'thix-id',
    storageBucket: 'thix-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxWeptLUmMXPk5UXlIU5InA_0O3R5qk4',
    appId: '1:27116360434:ios:e0f53c667476124743766b',
    messagingSenderId: '27116360434',
    projectId: 'thix-id',
    storageBucket: 'thix-id.firebasestorage.app',
    iosClientId: '27116360434-e3il3pf7mho0cabk3482hlr0vfmvsp1b.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
