-- THIX ID - Extended profile fields + linked tables (multi-entries)
-- هدف: توحيد الحقول (full_name, competence, experience) + إضافة حقول الهوية/البدن
-- + جداول مرتبطة: formations, experiences, contacts_urgence
--
-- This migration is idempotent (safe to re-run).

begin;

-- 1) Extend public.profiles
alter table if exists public.profiles
  add column if not exists full_name text,
  add column if not exists competence text,
  add column if not exists height text,
  add column if not exists weight text,
  add column if not exists blood_group text,
  add column if not exists has_physical_disability boolean,
  add column if not exists physical_disability_description text,
  add column if not exists national_id_number text,
  add column if not exists id_document_type text,
  add column if not exists id_document_issue_date text,
  add column if not exists id_document_expiry_date text,
  add column if not exists id_document_issue_place text;

-- 2) Linked tables (multi-entries)
-- Note: we use bigint identity PK to keep inserts simple from Flutter.

create table if not exists public.formations (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  payload jsonb not null default '{}'::jsonb,
  sort_index int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists formations_user_id_idx on public.formations (user_id);
create index if not exists formations_user_sort_idx on public.formations (user_id, sort_index);

create table if not exists public.experiences (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  payload jsonb not null default '{}'::jsonb,
  sort_index int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists experiences_user_id_idx on public.experiences (user_id);
create index if not exists experiences_user_sort_idx on public.experiences (user_id, sort_index);

create table if not exists public.contacts_urgence (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  payload jsonb not null default '{}'::jsonb,
  sort_index int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists contacts_urgence_user_id_idx on public.contacts_urgence (user_id);
create index if not exists contacts_urgence_user_sort_idx on public.contacts_urgence (user_id, sort_index);

-- 3) RLS policies
alter table if exists public.formations enable row level security;
alter table if exists public.experiences enable row level security;
alter table if exists public.contacts_urgence enable row level security;

-- SELECT: authenticated can read (Public View requires dynamic read)
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='formations' and policyname='formations_select_auth') then
    create policy formations_select_auth on public.formations for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='experiences' and policyname='experiences_select_auth') then
    create policy experiences_select_auth on public.experiences for select to authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='contacts_urgence' and policyname='contacts_urgence_select_auth') then
    create policy contacts_urgence_select_auth on public.contacts_urgence for select to authenticated using (true);
  end if;
end $$;

-- INSERT/UPDATE/DELETE: user can manage own rows
do $$
begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='formations' and policyname='formations_write_own') then
    create policy formations_write_own on public.formations
      for all to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='experiences' and policyname='experiences_write_own') then
    create policy experiences_write_own on public.experiences
      for all to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='contacts_urgence' and policyname='contacts_urgence_write_own') then
    create policy contacts_urgence_write_own on public.contacts_urgence
      for all to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

-- 4) Realtime: include tables in publication (best effort)
do $$
begin
  begin
    alter publication supabase_realtime add table public.formations;
  exception when duplicate_object then null;
  when undefined_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.experiences;
  exception when duplicate_object then null;
  when undefined_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.contacts_urgence;
  exception when duplicate_object then null;
  when undefined_object then null;
  end;
end $$;

commit;
